const quote = document.querySelector(".quote");
const btn = document.querySelector(".btn");

const quotes = [
    "Stay consistent.",
    "Discipline beats motivation.",
    "Small steps every day.",
    "Focus on progress, not perfection.",
    "Keep going no matter what.",
    "Dream big. Start small.",
    "Action creates clarity.",
    "Make it happen.",
    "Stay hungry.",
    "Work in silence.",
    "Consistency is key.",
    "Push yourself daily.",
    "Never settle.",
    "Stay focused.",
    "Do it anyway.",
    "Progress over perfection.",
    "Think big.",
    "Be relentless.",
    "Trust the process.",
    "Start now.",
    "Be better than yesterday.",
    "Keep building.",
    "Stay sharp.",
    "Level up daily.",
    "Don’t quit.",
    "Stay disciplined.",
    "Work smarter.",
    "Keep improving.",
    "Stay locked in.",
    "Be unstoppable.",
    "Stay driven.",
    "Make progress.",
    "Stay committed.",
    "Focus up.",
    "Keep learning.",
    "Stay hungry for more.",
    "Push past limits.",
    "Keep evolving.",
    "Stay dedicated.",
    "Stay in control.",
    "Keep moving forward.",
    "Outwork everyone.",
    "Stay ambitious.",
    "Keep grinding.",
    "Stay motivated.",
    "Be consistent.",
    "Work hard quietly.",
    "Stay patient.",
    "Keep your vision.",
    "Focus on goals.",
    "Stay determined.",
    "Keep pushing.",
    "Be disciplined.",
    "Stay confident.",
    "Keep hustling.",
    "Stay resilient.",
    "Keep striving.",
    "Stay inspired.",
    "Keep winning.",
    "Stay fearless.",
    "Keep growing.",
    "Stay creative.",
    "Keep dreaming.",
    "Stay strong.",
    "Keep building yourself.",
    "Stay focused on growth.",
    "Keep going forward.",
    "Stay determined always.",
    "Keep leveling up.",
    "Stay motivated daily.",
    "Keep pushing limits.",
    "Stay ambitious always.",
    "Keep improving daily.",
    "Stay strong mentally.",
    "Keep moving ahead.",
    "Stay consistent always.",
    "Keep evolving daily.",
    "Stay hungry always.",
    "Keep pushing forward.",
    "Stay focused always.",
    "Keep chasing goals.",
    "Stay driven always.",
    "Keep working hard.",
    "Stay committed always.",
    "Keep learning daily.",
    "Stay sharp always.",
    "Keep growing daily.",
    "Stay inspired always.",
    "Keep striving daily.",
    "Stay fearless always.",
    "Keep winning daily.",
    "Stay confident always.",
    "Keep hustling daily.",
    "Stay resilient always.",
    "Keep dreaming daily.",
    "Stay creative always.",
    "Keep building daily.",
    "Stay strong always.",
    "Keep moving daily.",
    "Stay determined daily.",
    "Keep progressing.",
    "Stay focused daily.",
    "Keep improving.",
    "Stay driven daily.",
    "Keep evolving.",
    "Stay ambitious daily.",
    "Keep pushing.",
    "Stay consistent daily.",
    "Keep striving.",
    "Stay motivated always.",
    "Keep growing always.",
    "Stay fearless daily.",
    "Keep learning always.",
    "Stay sharp daily.",
    "Keep building always.",
    "Stay creative daily.",
    "Keep dreaming always.",
    "Stay strong daily.",
    "Keep winning always.",
    "Stay confident daily.",
    "Keep hustling always.",
    "Stay resilient daily.",
    "Keep moving always.",
    "Stay determined always.",
    "Keep pushing always.",
    "Stay focused always.",
    "Keep improving always.",
    "Stay driven always.",
    "Keep evolving always.",
    "Stay ambitious always.",
    "Keep striving always.",
    "Stay motivated daily.",
    "Keep growing daily.",
    "Stay fearless always.",
    "Keep learning daily.",
    "Stay sharp always.",
    "Keep building daily.",
    "Stay creative always.",
    "Keep dreaming daily.",
    "Stay strong always.",
    "Keep winning daily.",
    "Stay confident always.",
    "Keep hustling daily.",
    "Stay resilient always.",
    "Keep moving daily.",
    "Stay determined always.",
    "Keep progressing daily.",
    "Stay focused always.",
    "Keep improving daily.",
    "Stay driven always.",
    "Keep evolving daily.",
    "Stay ambitious always.",
    "Keep striving daily.",
    "Stay motivated always.",
    "Keep growing always.",
    "Stay fearless daily.",
    "Keep learning always.",
    "Stay sharp daily.",
    "Keep building always.",
    "Stay creative daily.",
    "Keep dreaming always.",
    "Stay strong daily.",
    "Keep winning always.",
    "Stay confident daily.",
    "Keep hustling always.",
    "Stay resilient daily.",
    "Keep moving always.",
    "Stay determined daily.",
    "Keep progressing always.",
    "Stay focused daily.",
    "Keep improving always.",
    "Stay driven daily.",
    "Keep evolving always.",
    "Stay ambitious daily.",
    "Keep striving always.",
    "Stay motivated daily.",
    "Keep growing always.",
    "Stay fearless always.",
    "Keep learning daily.",
    "Stay sharp always.",
    "Keep building daily.",
    "Stay creative always.",
    "Keep dreaming daily.",
    "Stay strong always.",
    "Keep winning daily.",
    "Stay confident always.",
    "Keep hustling daily.",
    "Stay resilient always.",
    "Keep moving daily.",
    "Stay determined always."
];

function generateQuote() {
    const randomIndex = Math.floor(Math.random() * quotes.length);

    // fade out
    quote.style.opacity = 0;

    setTimeout(() => {
        // change text
        quote.textContent = quotes[randomIndex];

        // fade in
        quote.style.opacity = 1;
    }, 200);
}

btn.addEventListener("click", generateQuote);

// show one on load
generateQuote();
